"""Strolid Library - GPU utilities and helpers."""

from strolidlib.gpu import (
    is_cuda_available,
    is_tensor,
    is_numpy,
    is_pyannote_pipeline,
    numpy_to_tensor,
    move_to_gpu_maybe,
    set_cuda_device,
    set_cuda_device_maybe,
    get_cuda_device_count,
    get_current_cuda_device,
    cuda_synchronize,
    enable_tf32,
    is_mono,
    convert_to_mono,
    ensure_mono,
    resample_tensor,
    resample_tensor_maybe,
    tensor_to_contiguous,
    load_ambernet_model,
    predict_language_ambernet,
    strolid_model_name_to_nemo_model_name,
    load_nemo_model_maybe_refresh,
    load_transcription_model,
    load_langid_model,
    load_tensor_from_url,
    load_tensor_from_b64,
    dialog_to_tensor,
    move_to_cpu_maybe,
    move_to_device_maybe,
    preprocess_tensor,
    load_tensor_from_vcon,
    load_and_preprocess_tensor_from_vcon,
    transcribe_many,
    transcribe,
)

from strolidlib.utils import (
    seconds_to_ydhms,
    are_we_parallel,
    opts_have_changed,
    include_default_opts,
    get_first_dialog,
    is_valid_url,
    is_int,
)

__all__ = [
    # gpu.py exports
    "is_cuda_available",
    "is_tensor",
    "is_numpy",
    "is_pyannote_pipeline",
    "numpy_to_tensor",
    "move_to_gpu_maybe",
    "set_cuda_device",
    "set_cuda_device_maybe",
    "get_cuda_device_count",
    "get_current_cuda_device",
    "cuda_synchronize",
    "enable_tf32",
    "is_mono",
    "convert_to_mono",
    "ensure_mono",
    "resample_tensor",
    "resample_tensor_maybe",
    "tensor_to_contiguous",
    "load_ambernet_model",
    "predict_language_ambernet",
    "strolid_model_name_to_nemo_model_name",
    "load_nemo_model_maybe_refresh",
    "load_transcription_model",
    "load_langid_model",
    "load_tensor_from_url",
    "load_tensor_from_b64",
    "dialog_to_tensor",
    "move_to_cpu_maybe",
    "move_to_device_maybe",
    "preprocess_tensor",
    "load_tensor_from_vcon",
    "load_and_preprocess_tensor_from_vcon",
    "transcribe_many",
    "transcribe",
    # utils.py exports
    "seconds_to_ydhms",
    "are_we_parallel",
    "opts_have_changed",
    "include_default_opts",
    "get_first_dialog",
    "is_valid_url",
    "is_int",
]

